
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace STEP_PAY.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Accounts
{

    public int Id { get; set; }

    public int UserId { get; set; }

    public string Login { get; set; }

    public string Password { get; set; }



    public virtual Users Users { get; set; }

}

}
