//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STEP_PAY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cards
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cards()
        {
            this.Expenses = new HashSet<Expenses>();
        }
    
        public int Id { get; set; }
        public decimal Money { get; set; }
        public int UserId { get; set; }
        public int PinCode { get; set; }
        public System.DateTime ExpiredDate { get; set; }
        public string Currency { get; set; }
        public string Title { get; set; }
        public string Number { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expenses> Expenses { get; set; }
    }
}
