

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace STEP_PAY.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class STEP_PAYEntities : DbContext
{
    public STEP_PAYEntities()
        : base("name=STEP_PAYEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Accounts> Accounts { get; set; }

    public virtual DbSet<Cards> Cards { get; set; }

    public virtual DbSet<Expenses> Expenses { get; set; }

    public virtual DbSet<Users> Users { get; set; }

}

}

